version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      # Set admin credentials
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - "8080:8080"
