version: '3.8'

services:
  strapi:
    container_name: strapi
    build: .
    working_dir: /srv/app
    volumes:
      - .:/srv/app
      - /srv/app/node_modules  # Prevents mounting issues with node_modules
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=development
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=admin  # Must match Postgres user
      - DATABASE_PASSWORD=adminPassword25  # Must match Postgres password
    depends_on:
      - db
    command: yarn develop

  db:
    container_name: postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: admin  # Must match Strapi username
      POSTGRES_PASSWORD: adminPassword25  # Must match Strapi password
      POSTGRES_DB: strapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
